/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Premium color system inspired by Stripe, Linear, Vercel
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        // Maintain existing color system for compatibility
        "on-primary": "#ffffff",
        "secondary": "#006a61",
        "inverse-primary": "#c3c0ff",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#4b4dd8",
        "outline-variant": "#c7c4d8",
        "primary": {
          DEFAULT: "#4f46e5",
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#1e1b4b",
        },
        "primary-fixed": "#e2dfff",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-primary-fixed-variant": "#3323cc",
        "on-background": "#131b2e",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "on-secondary-fixed-variant": "#005049",
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#d9d8ff",
        "on-secondary": "#ffffff",
        "on-surface": "#131b2e",
        "secondary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed": "#07006c",
        "outline": "#777587",
        "on-surface-variant": "#464555",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary": "#3130c0",
        "surface-variant": "#dae2fd",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201d",
        "on-primary-container": "#dad7ff",
        "inverse-surface": "#283044",
        "primary-container": "#4f46e5",
        "background": "#faf8ff",
        "tertiary-fixed": "#e1e0ff",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed": "#89f5e7",
        "on-secondary-container": "#006f66",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-high": "#e2e7ff"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(99, 102, 241, 0.6)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
