/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "secondary": "#006a61",
        "inverse-primary": "#c3c0ff",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#4b4dd8",
        "outline-variant": "#c7c4d8",
        "primary": {
          DEFAULT: "#3525cd",
          50: "#f0effb",
          100: "#e2e0f7",
          200: "#c7c4f0",
          300: "#a39de6",
          400: "#796fd7",
          500: "#5446c8",
          600: "#3525cd",
          650: "#2e1fae",
          700: "#2a1da6",
          750: "#23188d",
          800: "#23188d",
          900: "#1c1274",
          950: "#0f094c",
        },
        "primary-fixed": "#e2dfff",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-primary-fixed-variant": "#3323cc",
        "on-background": "#131b2e",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "on-secondary-fixed-variant": "#005049",
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#d9d8ff",
        "on-secondary": "#ffffff",
        "on-surface": "#131b2e",
        "secondary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed": "#07006c",
        "outline": "#777587",
        "on-surface-variant": "#464555",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#c0c1ff",
        "tertiary": "#3130c0",
        "surface-variant": "#dae2fd",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201d",
        "on-primary-container": "#dad7ff",
        "inverse-surface": "#283044",
        "primary-container": "#4f46e5",
        "background": "#faf8ff",
        "tertiary-fixed": "#e1e0ff",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed": "#89f5e7",
        "on-secondary-container": "#006f66",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-high": "#e2e7ff"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
